name: Fury

on:
  workflow_dispatch:
  push:
    tags: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
      env:
        GOPROXY: https://${{ secrets.FURY_TOKEN }}@go-proxy.fury.io/a-poor/
        GOPRIVATE: "git.fury.io/a-poor/*"
        GONOPROXY: none
